package dev.dudie.buddybot.logic;

public enum RescueAbility {
    HOSTILE_DEFENSE,
    PROJECTILE_BLOCK,
    CLIFF_COBWEB,
    ESCAPE_BREAK,
    FALL_CLUTCH,
    HAZARD_COVER,
    SUPPORT_POTION,
    PEARL_REPOSITION,
    SLOW_FALLING,
    CATCH_PLATFORM,
    EXPLOSION_SHIELD
}
